### PR TITLE
[OC-1431] Display names rather than IDs for entities/groups in the users table

### PR DESCRIPTION
**Pull request by AlexGuironnetRTE**
I ended up refactoring the components a bit for this ticket, but with perimeters round the corner (OC-1089) I wanted to make things as easy to extend as possible.

Release notes:
Under features, OC-1431 - Display names rather than IDs for entities/groups in the users table (Administration)

### CODE REVIEW

**Review by quinarygio — COMMENTED** [review]
After deleting a Group or an Entity they are still listed in User modal dropdowns, I think they should be removed also  from the cached values.

**Comment by AlexGuironnetRTE** [comment]
> After deleting a Group or an Entity they are still listed in User modal dropdowns, I think they should be removed also from the cached values.

That's right thanks! Would you rather I pushed the fix on a separate commit or did an amend and force-push?

**Comment by quinarygio** [comment]
> > After deleting a Group or an Entity they are still listed in User modal dropdowns, I think they should be removed also from the cached values.
> 
> That's right thanks! Would you rather I pushed the fix on a separate commit or did an amend and force-push?

Maybe better to squash and force push

**Comment by AlexGuironnetRTE** [comment]
Done!

**Review by quinarygio — APPROVED** [review]

**Pull request merged**
