### PR TITLE
[FE-1302] update kafka avro

### PR DESCRIPTION
**Pull request by JeroenGommans**
Updated minor version for Confluent Schema client and AVRO serializer, as renovate suggested

Signed-off-by: Jeroen Gommans <jeroen@anjersoftwaredesign.nl>

### CODE REVIEW

**Comment by JeroenGommans** [comment]
Forger to check PR #1180 and #1186  too, but I cannot undo the Pull Request. Please do not merge yet.

**Comment by AlexGuironnetRTE** [comment]
> Forger to check PR #1180 and #1186 too, but I cannot undo the Pull Request. Please do not merge yet.

Noted, I converted it to a draft PR.

**Comment by JeroenGommans** [comment]
Thanks! I finished updating the files.
I am not sure if renovate automatically closes the PRs it created, otherwise you can close
- #1180 
- #1186 
- #1371 
- #1424 

That is, if you agree with the changes :)

**Comment by AlexGuironnetRTE** [comment]
> Thanks! I finished updating the files.
> I am not sure if renovate automatically closes the PRs it created, otherwise you can close
> 
>     * [Update dependency org.apache.avro:avro to v1.10.2 #1180](https://github.com/opfab/operatorfabric-core/pull/1180)
> 
>     * [Update dependency com.commercehub.gradle.plugin:gradle-avro-plugin to v0.99.99 #1186](https://github.com/opfab/operatorfabric-core/pull/1186)
> 
>     * [Update dependency io.confluent:kafka-avro-serializer to v5.5.5 #1371](https://github.com/opfab/operatorfabric-core/pull/1371)
> 
>     * [Update dependency io.confluent:kafka-schema-registry-client to v5.5.5 #1424](https://github.com/opfab/operatorfabric-core/pull/1424)
> 
> 
> That is, if you agree with the changes :)

Thanks again for the PR. Yes, Renovate should close the PRs automatically when it runs tonight, it's a good opportunity to check that it works ;-) If not I'll close them.

**Pull request merged**
