### PR TITLE
Integrate resizable columns for table using ag-grid (#5648)

### PR DESCRIPTION
**Pull request by vlo-rte**
Nothing in release notes.

### CODE REVIEW

**Comment by freddidierRTE** [comment]
Should not be possible to adjust the last column in admin screen 

image

**Comment by freddidierRTE** [comment]
After making a few test , i would prefer first to let the column resizing feature available only for admin screen and we will see later if we open the feature in other screens

**Comment by vlo-rte** [comment]
> Should not be possible to adjust the last column in admin screen
> 
> image

Done.

**Comment by vlo-rte** [comment]
> After making a few test , i would prefer first to let the column resizing feature available only for admin screen and we will see later if we open the feature in other screens

Done.

**Review by vlo-rte — COMMENTED** [review]
PR validated by Frederic Didier.

**Pull request merged**
