### PR TITLE
add in archives view/export new field (#4368)

### PR DESCRIPTION
**Pull request by HubertDuchatelle**
- In release note :
  -  In chapter :  Features
  -  Text : #4368 In archives view / export : removed field business period, added fields publisher, entity recipients and process

### CODE REVIEW

**Comment by vlo-rte** [comment]
Please can you add space between name of columns, in this example, "publication date" and "emitter" are too near 
image

**Comment by vlo-rte** [comment]
Can you make an update to not have words broken ? In this example, we have 
"ELECTRICITY CONSUMPTION FORECAST" which is broken and also "Result of the maintenance is <OK>" which is also broken
image

**Review by vlo-rte — CHANGES_REQUESTED** [review]
Please see my remarks.

**Comment by vlo-rte** [comment]
In archives.spec.js, can you test also the "process column"  please ?

**Review by vlo-rte — CHANGES_REQUESTED** [review]
In archives.spec.js, can you test also the "process column" please ?

**Comment by HubertDuchatelle** [comment]
To discuss with Frédéric:
- words break and columns width

**Pull request merged**
